/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.argolabs.ai.api.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum DietaryLabel {
    VEGAN("VEGAN"),

    VEGETARIAN("VEGETARIAN"),

    GLUTEN_FREE("GLUTEN_FREE");

    private final String value;

    DietaryLabel(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
