/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.argolabs.ai.api.types;

import com.argolabs.ai.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = MenuFlat.Builder.class)
public final class MenuFlat {
    private final String externalId;

    private final Optional<MultilingualText> name;

    private final Optional<List<String>> categoryExternalIds;

    private final List<Availability> availability;

    private final int id;

    private final Map<String, Object> additionalProperties;

    private MenuFlat(
            String externalId,
            Optional<MultilingualText> name,
            Optional<List<String>> categoryExternalIds,
            List<Availability> availability,
            int id,
            Map<String, Object> additionalProperties) {
        this.externalId = externalId;
        this.name = name;
        this.categoryExternalIds = categoryExternalIds;
        this.availability = availability;
        this.id = id;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("external_id")
    public String getExternalId() {
        return externalId;
    }

    @JsonProperty("name")
    public Optional<MultilingualText> getName() {
        return name;
    }

    @JsonProperty("category_external_ids")
    public Optional<List<String>> getCategoryExternalIds() {
        return categoryExternalIds;
    }

    @JsonProperty("availability")
    public List<Availability> getAvailability() {
        return availability;
    }

    @JsonProperty("id")
    public int getId() {
        return id;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof MenuFlat && equalTo((MenuFlat) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(MenuFlat other) {
        return externalId.equals(other.externalId)
                && name.equals(other.name)
                && categoryExternalIds.equals(other.categoryExternalIds)
                && availability.equals(other.availability)
                && id == other.id;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.externalId, this.name, this.categoryExternalIds, this.availability, this.id);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ExternalIdStage builder() {
        return new Builder();
    }

    public interface ExternalIdStage {
        IdStage externalId(String externalId);

        Builder from(MenuFlat other);
    }

    public interface IdStage {
        _FinalStage id(int id);
    }

    public interface _FinalStage {
        MenuFlat build();

        _FinalStage name(Optional<MultilingualText> name);

        _FinalStage name(MultilingualText name);

        _FinalStage categoryExternalIds(Optional<List<String>> categoryExternalIds);

        _FinalStage categoryExternalIds(List<String> categoryExternalIds);

        _FinalStage availability(List<Availability> availability);

        _FinalStage addAvailability(Availability availability);

        _FinalStage addAllAvailability(List<Availability> availability);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ExternalIdStage, IdStage, _FinalStage {
        private String externalId;

        private int id;

        private List<Availability> availability = new ArrayList<>();

        private Optional<List<String>> categoryExternalIds = Optional.empty();

        private Optional<MultilingualText> name = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(MenuFlat other) {
            externalId(other.getExternalId());
            name(other.getName());
            categoryExternalIds(other.getCategoryExternalIds());
            availability(other.getAvailability());
            id(other.getId());
            return this;
        }

        @java.lang.Override
        @JsonSetter("external_id")
        public IdStage externalId(String externalId) {
            this.externalId = externalId;
            return this;
        }

        @java.lang.Override
        @JsonSetter("id")
        public _FinalStage id(int id) {
            this.id = id;
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllAvailability(List<Availability> availability) {
            this.availability.addAll(availability);
            return this;
        }

        @java.lang.Override
        public _FinalStage addAvailability(Availability availability) {
            this.availability.add(availability);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "availability", nulls = Nulls.SKIP)
        public _FinalStage availability(List<Availability> availability) {
            this.availability.clear();
            this.availability.addAll(availability);
            return this;
        }

        @java.lang.Override
        public _FinalStage categoryExternalIds(List<String> categoryExternalIds) {
            this.categoryExternalIds = Optional.ofNullable(categoryExternalIds);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "category_external_ids", nulls = Nulls.SKIP)
        public _FinalStage categoryExternalIds(Optional<List<String>> categoryExternalIds) {
            this.categoryExternalIds = categoryExternalIds;
            return this;
        }

        @java.lang.Override
        public _FinalStage name(MultilingualText name) {
            this.name = Optional.ofNullable(name);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "name", nulls = Nulls.SKIP)
        public _FinalStage name(Optional<MultilingualText> name) {
            this.name = name;
            return this;
        }

        @java.lang.Override
        public MenuFlat build() {
            return new MenuFlat(externalId, name, categoryExternalIds, availability, id, additionalProperties);
        }
    }
}
