/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.argolabs.ai.api.types;

import com.argolabs.ai.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ModifierGroupTree.Builder.class)
public final class ModifierGroupTree {
    private final int id;

    private final String externalId;

    private final String type;

    private final MultilingualText name;

    private final Optional<MultilingualText> description;

    private final int groupMax;

    private final int groupMin;

    private final int chargeAfter;

    private final List<ModifierItemTree> modifierItems;

    private final Map<String, Object> additionalProperties;

    private ModifierGroupTree(
            int id,
            String externalId,
            String type,
            MultilingualText name,
            Optional<MultilingualText> description,
            int groupMax,
            int groupMin,
            int chargeAfter,
            List<ModifierItemTree> modifierItems,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.externalId = externalId;
        this.type = type;
        this.name = name;
        this.description = description;
        this.groupMax = groupMax;
        this.groupMin = groupMin;
        this.chargeAfter = chargeAfter;
        this.modifierItems = modifierItems;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("id")
    public int getId() {
        return id;
    }

    @JsonProperty("external_id")
    public String getExternalId() {
        return externalId;
    }

    @JsonProperty("type")
    public String getType() {
        return type;
    }

    @JsonProperty("name")
    public MultilingualText getName() {
        return name;
    }

    @JsonProperty("description")
    public Optional<MultilingualText> getDescription() {
        return description;
    }

    @JsonProperty("group_max")
    public int getGroupMax() {
        return groupMax;
    }

    @JsonProperty("group_min")
    public int getGroupMin() {
        return groupMin;
    }

    @JsonProperty("charge_after")
    public int getChargeAfter() {
        return chargeAfter;
    }

    @JsonProperty("modifier_items")
    public List<ModifierItemTree> getModifierItems() {
        return modifierItems;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ModifierGroupTree && equalTo((ModifierGroupTree) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ModifierGroupTree other) {
        return id == other.id
                && externalId.equals(other.externalId)
                && type.equals(other.type)
                && name.equals(other.name)
                && description.equals(other.description)
                && groupMax == other.groupMax
                && groupMin == other.groupMin
                && chargeAfter == other.chargeAfter
                && modifierItems.equals(other.modifierItems);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.id,
                this.externalId,
                this.type,
                this.name,
                this.description,
                this.groupMax,
                this.groupMin,
                this.chargeAfter,
                this.modifierItems);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        ExternalIdStage id(int id);

        Builder from(ModifierGroupTree other);
    }

    public interface ExternalIdStage {
        TypeStage externalId(String externalId);
    }

    public interface TypeStage {
        NameStage type(String type);
    }

    public interface NameStage {
        GroupMaxStage name(MultilingualText name);
    }

    public interface GroupMaxStage {
        GroupMinStage groupMax(int groupMax);
    }

    public interface GroupMinStage {
        ChargeAfterStage groupMin(int groupMin);
    }

    public interface ChargeAfterStage {
        _FinalStage chargeAfter(int chargeAfter);
    }

    public interface _FinalStage {
        ModifierGroupTree build();

        _FinalStage description(Optional<MultilingualText> description);

        _FinalStage description(MultilingualText description);

        _FinalStage modifierItems(List<ModifierItemTree> modifierItems);

        _FinalStage addModifierItems(ModifierItemTree modifierItems);

        _FinalStage addAllModifierItems(List<ModifierItemTree> modifierItems);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements IdStage,
                    ExternalIdStage,
                    TypeStage,
                    NameStage,
                    GroupMaxStage,
                    GroupMinStage,
                    ChargeAfterStage,
                    _FinalStage {
        private int id;

        private String externalId;

        private String type;

        private MultilingualText name;

        private int groupMax;

        private int groupMin;

        private int chargeAfter;

        private List<ModifierItemTree> modifierItems = new ArrayList<>();

        private Optional<MultilingualText> description = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ModifierGroupTree other) {
            id(other.getId());
            externalId(other.getExternalId());
            type(other.getType());
            name(other.getName());
            description(other.getDescription());
            groupMax(other.getGroupMax());
            groupMin(other.getGroupMin());
            chargeAfter(other.getChargeAfter());
            modifierItems(other.getModifierItems());
            return this;
        }

        @java.lang.Override
        @JsonSetter("id")
        public ExternalIdStage id(int id) {
            this.id = id;
            return this;
        }

        @java.lang.Override
        @JsonSetter("external_id")
        public TypeStage externalId(String externalId) {
            this.externalId = externalId;
            return this;
        }

        @java.lang.Override
        @JsonSetter("type")
        public NameStage type(String type) {
            this.type = type;
            return this;
        }

        @java.lang.Override
        @JsonSetter("name")
        public GroupMaxStage name(MultilingualText name) {
            this.name = name;
            return this;
        }

        @java.lang.Override
        @JsonSetter("group_max")
        public GroupMinStage groupMax(int groupMax) {
            this.groupMax = groupMax;
            return this;
        }

        @java.lang.Override
        @JsonSetter("group_min")
        public ChargeAfterStage groupMin(int groupMin) {
            this.groupMin = groupMin;
            return this;
        }

        @java.lang.Override
        @JsonSetter("charge_after")
        public _FinalStage chargeAfter(int chargeAfter) {
            this.chargeAfter = chargeAfter;
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllModifierItems(List<ModifierItemTree> modifierItems) {
            this.modifierItems.addAll(modifierItems);
            return this;
        }

        @java.lang.Override
        public _FinalStage addModifierItems(ModifierItemTree modifierItems) {
            this.modifierItems.add(modifierItems);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "modifier_items", nulls = Nulls.SKIP)
        public _FinalStage modifierItems(List<ModifierItemTree> modifierItems) {
            this.modifierItems.clear();
            this.modifierItems.addAll(modifierItems);
            return this;
        }

        @java.lang.Override
        public _FinalStage description(MultilingualText description) {
            this.description = Optional.ofNullable(description);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "description", nulls = Nulls.SKIP)
        public _FinalStage description(Optional<MultilingualText> description) {
            this.description = description;
            return this;
        }

        @java.lang.Override
        public ModifierGroupTree build() {
            return new ModifierGroupTree(
                    id,
                    externalId,
                    type,
                    name,
                    description,
                    groupMax,
                    groupMin,
                    chargeAfter,
                    modifierItems,
                    additionalProperties);
        }
    }
}
