/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.argolabs.ai.api.types;

import com.argolabs.ai.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = OrdersResponse.Builder.class)
public final class OrdersResponse {
    private final Optional<String> resultCode;

    private final Optional<String> resultMessage;

    private final Optional<List<OrderDetailWithArgoId>> orderResultList;

    private final int pageIndex;

    private final int pageSize;

    private final int count;

    private final Map<String, Object> additionalProperties;

    private OrdersResponse(
            Optional<String> resultCode,
            Optional<String> resultMessage,
            Optional<List<OrderDetailWithArgoId>> orderResultList,
            int pageIndex,
            int pageSize,
            int count,
            Map<String, Object> additionalProperties) {
        this.resultCode = resultCode;
        this.resultMessage = resultMessage;
        this.orderResultList = orderResultList;
        this.pageIndex = pageIndex;
        this.pageSize = pageSize;
        this.count = count;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("result_code")
    public Optional<String> getResultCode() {
        return resultCode;
    }

    @JsonProperty("result_message")
    public Optional<String> getResultMessage() {
        return resultMessage;
    }

    @JsonProperty("order_result_list")
    public Optional<List<OrderDetailWithArgoId>> getOrderResultList() {
        return orderResultList;
    }

    @JsonProperty("page_index")
    public int getPageIndex() {
        return pageIndex;
    }

    @JsonProperty("page_size")
    public int getPageSize() {
        return pageSize;
    }

    @JsonProperty("count")
    public int getCount() {
        return count;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof OrdersResponse && equalTo((OrdersResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(OrdersResponse other) {
        return resultCode.equals(other.resultCode)
                && resultMessage.equals(other.resultMessage)
                && orderResultList.equals(other.orderResultList)
                && pageIndex == other.pageIndex
                && pageSize == other.pageSize
                && count == other.count;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.resultCode, this.resultMessage, this.orderResultList, this.pageIndex, this.pageSize, this.count);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static PageIndexStage builder() {
        return new Builder();
    }

    public interface PageIndexStage {
        PageSizeStage pageIndex(int pageIndex);

        Builder from(OrdersResponse other);
    }

    public interface PageSizeStage {
        CountStage pageSize(int pageSize);
    }

    public interface CountStage {
        _FinalStage count(int count);
    }

    public interface _FinalStage {
        OrdersResponse build();

        _FinalStage resultCode(Optional<String> resultCode);

        _FinalStage resultCode(String resultCode);

        _FinalStage resultMessage(Optional<String> resultMessage);

        _FinalStage resultMessage(String resultMessage);

        _FinalStage orderResultList(Optional<List<OrderDetailWithArgoId>> orderResultList);

        _FinalStage orderResultList(List<OrderDetailWithArgoId> orderResultList);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements PageIndexStage, PageSizeStage, CountStage, _FinalStage {
        private int pageIndex;

        private int pageSize;

        private int count;

        private Optional<List<OrderDetailWithArgoId>> orderResultList = Optional.empty();

        private Optional<String> resultMessage = Optional.empty();

        private Optional<String> resultCode = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(OrdersResponse other) {
            resultCode(other.getResultCode());
            resultMessage(other.getResultMessage());
            orderResultList(other.getOrderResultList());
            pageIndex(other.getPageIndex());
            pageSize(other.getPageSize());
            count(other.getCount());
            return this;
        }

        @java.lang.Override
        @JsonSetter("page_index")
        public PageSizeStage pageIndex(int pageIndex) {
            this.pageIndex = pageIndex;
            return this;
        }

        @java.lang.Override
        @JsonSetter("page_size")
        public CountStage pageSize(int pageSize) {
            this.pageSize = pageSize;
            return this;
        }

        @java.lang.Override
        @JsonSetter("count")
        public _FinalStage count(int count) {
            this.count = count;
            return this;
        }

        @java.lang.Override
        public _FinalStage orderResultList(List<OrderDetailWithArgoId> orderResultList) {
            this.orderResultList = Optional.ofNullable(orderResultList);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "order_result_list", nulls = Nulls.SKIP)
        public _FinalStage orderResultList(Optional<List<OrderDetailWithArgoId>> orderResultList) {
            this.orderResultList = orderResultList;
            return this;
        }

        @java.lang.Override
        public _FinalStage resultMessage(String resultMessage) {
            this.resultMessage = Optional.ofNullable(resultMessage);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "result_message", nulls = Nulls.SKIP)
        public _FinalStage resultMessage(Optional<String> resultMessage) {
            this.resultMessage = resultMessage;
            return this;
        }

        @java.lang.Override
        public _FinalStage resultCode(String resultCode) {
            this.resultCode = Optional.ofNullable(resultCode);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "result_code", nulls = Nulls.SKIP)
        public _FinalStage resultCode(Optional<String> resultCode) {
            this.resultCode = resultCode;
            return this;
        }

        @java.lang.Override
        public OrdersResponse build() {
            return new OrdersResponse(
                    resultCode, resultMessage, orderResultList, pageIndex, pageSize, count, additionalProperties);
        }
    }
}
