/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.argolabs.ai.api.types;

import com.argolabs.ai.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = OrderDetailResponse.Builder.class)
public final class OrderDetailResponse {
    private final OffsetDateTime createdAt;

    private final String id;

    private final StorePartialInfoWithArgoId store;

    private final CustomerBase customer;

    private final OrderStatusEnum status;

    private final int price;

    private final int tax;

    private final List<Map<String, Object>> items;

    private final Optional<String> customerComments;

    private final OffsetDateTime readyBy;

    private final Optional<OffsetDateTime> completedAt;

    private final boolean isRead;

    private final boolean inPos;

    private final String resultCode;

    private final String resultMessage;

    private final Map<String, Object> additionalProperties;

    private OrderDetailResponse(
            OffsetDateTime createdAt,
            String id,
            StorePartialInfoWithArgoId store,
            CustomerBase customer,
            OrderStatusEnum status,
            int price,
            int tax,
            List<Map<String, Object>> items,
            Optional<String> customerComments,
            OffsetDateTime readyBy,
            Optional<OffsetDateTime> completedAt,
            boolean isRead,
            boolean inPos,
            String resultCode,
            String resultMessage,
            Map<String, Object> additionalProperties) {
        this.createdAt = createdAt;
        this.id = id;
        this.store = store;
        this.customer = customer;
        this.status = status;
        this.price = price;
        this.tax = tax;
        this.items = items;
        this.customerComments = customerComments;
        this.readyBy = readyBy;
        this.completedAt = completedAt;
        this.isRead = isRead;
        this.inPos = inPos;
        this.resultCode = resultCode;
        this.resultMessage = resultMessage;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("created_at")
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    @JsonProperty("id")
    public String getId() {
        return id;
    }

    @JsonProperty("store")
    public StorePartialInfoWithArgoId getStore() {
        return store;
    }

    @JsonProperty("customer")
    public CustomerBase getCustomer() {
        return customer;
    }

    @JsonProperty("status")
    public OrderStatusEnum getStatus() {
        return status;
    }

    @JsonProperty("price")
    public int getPrice() {
        return price;
    }

    @JsonProperty("tax")
    public int getTax() {
        return tax;
    }

    @JsonProperty("items")
    public List<Map<String, Object>> getItems() {
        return items;
    }

    @JsonProperty("customer_comments")
    public Optional<String> getCustomerComments() {
        return customerComments;
    }

    @JsonProperty("ready_by")
    public OffsetDateTime getReadyBy() {
        return readyBy;
    }

    @JsonProperty("completed_at")
    public Optional<OffsetDateTime> getCompletedAt() {
        return completedAt;
    }

    @JsonProperty("is_read")
    public boolean getIsRead() {
        return isRead;
    }

    @JsonProperty("in_pos")
    public boolean getInPos() {
        return inPos;
    }

    @JsonProperty("result_code")
    public String getResultCode() {
        return resultCode;
    }

    @JsonProperty("result_message")
    public String getResultMessage() {
        return resultMessage;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof OrderDetailResponse && equalTo((OrderDetailResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(OrderDetailResponse other) {
        return createdAt.equals(other.createdAt)
                && id.equals(other.id)
                && store.equals(other.store)
                && customer.equals(other.customer)
                && status.equals(other.status)
                && price == other.price
                && tax == other.tax
                && items.equals(other.items)
                && customerComments.equals(other.customerComments)
                && readyBy.equals(other.readyBy)
                && completedAt.equals(other.completedAt)
                && isRead == other.isRead
                && inPos == other.inPos
                && resultCode.equals(other.resultCode)
                && resultMessage.equals(other.resultMessage);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.createdAt,
                this.id,
                this.store,
                this.customer,
                this.status,
                this.price,
                this.tax,
                this.items,
                this.customerComments,
                this.readyBy,
                this.completedAt,
                this.isRead,
                this.inPos,
                this.resultCode,
                this.resultMessage);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static CreatedAtStage builder() {
        return new Builder();
    }

    public interface CreatedAtStage {
        IdStage createdAt(OffsetDateTime createdAt);

        Builder from(OrderDetailResponse other);
    }

    public interface IdStage {
        StoreStage id(String id);
    }

    public interface StoreStage {
        CustomerStage store(StorePartialInfoWithArgoId store);
    }

    public interface CustomerStage {
        StatusStage customer(CustomerBase customer);
    }

    public interface StatusStage {
        PriceStage status(OrderStatusEnum status);
    }

    public interface PriceStage {
        TaxStage price(int price);
    }

    public interface TaxStage {
        ReadyByStage tax(int tax);
    }

    public interface ReadyByStage {
        IsReadStage readyBy(OffsetDateTime readyBy);
    }

    public interface IsReadStage {
        InPosStage isRead(boolean isRead);
    }

    public interface InPosStage {
        ResultCodeStage inPos(boolean inPos);
    }

    public interface ResultCodeStage {
        ResultMessageStage resultCode(String resultCode);
    }

    public interface ResultMessageStage {
        _FinalStage resultMessage(String resultMessage);
    }

    public interface _FinalStage {
        OrderDetailResponse build();

        _FinalStage items(List<Map<String, Object>> items);

        _FinalStage addItems(Map<String, Object> items);

        _FinalStage addAllItems(List<Map<String, Object>> items);

        _FinalStage customerComments(Optional<String> customerComments);

        _FinalStage customerComments(String customerComments);

        _FinalStage completedAt(Optional<OffsetDateTime> completedAt);

        _FinalStage completedAt(OffsetDateTime completedAt);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements CreatedAtStage,
                    IdStage,
                    StoreStage,
                    CustomerStage,
                    StatusStage,
                    PriceStage,
                    TaxStage,
                    ReadyByStage,
                    IsReadStage,
                    InPosStage,
                    ResultCodeStage,
                    ResultMessageStage,
                    _FinalStage {
        private OffsetDateTime createdAt;

        private String id;

        private StorePartialInfoWithArgoId store;

        private CustomerBase customer;

        private OrderStatusEnum status;

        private int price;

        private int tax;

        private OffsetDateTime readyBy;

        private boolean isRead;

        private boolean inPos;

        private String resultCode;

        private String resultMessage;

        private Optional<OffsetDateTime> completedAt = Optional.empty();

        private Optional<String> customerComments = Optional.empty();

        private List<Map<String, Object>> items = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(OrderDetailResponse other) {
            createdAt(other.getCreatedAt());
            id(other.getId());
            store(other.getStore());
            customer(other.getCustomer());
            status(other.getStatus());
            price(other.getPrice());
            tax(other.getTax());
            items(other.getItems());
            customerComments(other.getCustomerComments());
            readyBy(other.getReadyBy());
            completedAt(other.getCompletedAt());
            isRead(other.getIsRead());
            inPos(other.getInPos());
            resultCode(other.getResultCode());
            resultMessage(other.getResultMessage());
            return this;
        }

        @java.lang.Override
        @JsonSetter("created_at")
        public IdStage createdAt(OffsetDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        @java.lang.Override
        @JsonSetter("id")
        public StoreStage id(String id) {
            this.id = id;
            return this;
        }

        @java.lang.Override
        @JsonSetter("store")
        public CustomerStage store(StorePartialInfoWithArgoId store) {
            this.store = store;
            return this;
        }

        @java.lang.Override
        @JsonSetter("customer")
        public StatusStage customer(CustomerBase customer) {
            this.customer = customer;
            return this;
        }

        @java.lang.Override
        @JsonSetter("status")
        public PriceStage status(OrderStatusEnum status) {
            this.status = status;
            return this;
        }

        @java.lang.Override
        @JsonSetter("price")
        public TaxStage price(int price) {
            this.price = price;
            return this;
        }

        @java.lang.Override
        @JsonSetter("tax")
        public ReadyByStage tax(int tax) {
            this.tax = tax;
            return this;
        }

        @java.lang.Override
        @JsonSetter("ready_by")
        public IsReadStage readyBy(OffsetDateTime readyBy) {
            this.readyBy = readyBy;
            return this;
        }

        @java.lang.Override
        @JsonSetter("is_read")
        public InPosStage isRead(boolean isRead) {
            this.isRead = isRead;
            return this;
        }

        @java.lang.Override
        @JsonSetter("in_pos")
        public ResultCodeStage inPos(boolean inPos) {
            this.inPos = inPos;
            return this;
        }

        @java.lang.Override
        @JsonSetter("result_code")
        public ResultMessageStage resultCode(String resultCode) {
            this.resultCode = resultCode;
            return this;
        }

        @java.lang.Override
        @JsonSetter("result_message")
        public _FinalStage resultMessage(String resultMessage) {
            this.resultMessage = resultMessage;
            return this;
        }

        @java.lang.Override
        public _FinalStage completedAt(OffsetDateTime completedAt) {
            this.completedAt = Optional.ofNullable(completedAt);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "completed_at", nulls = Nulls.SKIP)
        public _FinalStage completedAt(Optional<OffsetDateTime> completedAt) {
            this.completedAt = completedAt;
            return this;
        }

        @java.lang.Override
        public _FinalStage customerComments(String customerComments) {
            this.customerComments = Optional.ofNullable(customerComments);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "customer_comments", nulls = Nulls.SKIP)
        public _FinalStage customerComments(Optional<String> customerComments) {
            this.customerComments = customerComments;
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllItems(List<Map<String, Object>> items) {
            this.items.addAll(items);
            return this;
        }

        @java.lang.Override
        public _FinalStage addItems(Map<String, Object> items) {
            this.items.add(items);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "items", nulls = Nulls.SKIP)
        public _FinalStage items(List<Map<String, Object>> items) {
            this.items.clear();
            this.items.addAll(items);
            return this;
        }

        @java.lang.Override
        public OrderDetailResponse build() {
            return new OrderDetailResponse(
                    createdAt,
                    id,
                    store,
                    customer,
                    status,
                    price,
                    tax,
                    items,
                    customerComments,
                    readyBy,
                    completedAt,
                    isRead,
                    inPos,
                    resultCode,
                    resultMessage,
                    additionalProperties);
        }
    }
}
