/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.argolabs.ai.api.types;

import com.argolabs.ai.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = RestaurantConfigurationResponse.Builder.class)
public final class RestaurantConfigurationResponse {
    private final Optional<CuisineTypeSchema> cuisineType;

    private final Map<String, Object> additionalProperties;

    private RestaurantConfigurationResponse(
            Optional<CuisineTypeSchema> cuisineType, Map<String, Object> additionalProperties) {
        this.cuisineType = cuisineType;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("cuisine_type")
    public Optional<CuisineTypeSchema> getCuisineType() {
        return cuisineType;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof RestaurantConfigurationResponse && equalTo((RestaurantConfigurationResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(RestaurantConfigurationResponse other) {
        return cuisineType.equals(other.cuisineType);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.cuisineType);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<CuisineTypeSchema> cuisineType = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(RestaurantConfigurationResponse other) {
            cuisineType(other.getCuisineType());
            return this;
        }

        @JsonSetter(value = "cuisine_type", nulls = Nulls.SKIP)
        public Builder cuisineType(Optional<CuisineTypeSchema> cuisineType) {
            this.cuisineType = cuisineType;
            return this;
        }

        public Builder cuisineType(CuisineTypeSchema cuisineType) {
            this.cuisineType = Optional.ofNullable(cuisineType);
            return this;
        }

        public RestaurantConfigurationResponse build() {
            return new RestaurantConfigurationResponse(cuisineType, additionalProperties);
        }
    }
}
