/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.argolabs.ai.api.types;

import com.argolabs.ai.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = StoreMenuResponseTree.Builder.class)
public final class StoreMenuResponseTree {
    private final List<MenuTree> menuConfiguration;

    private final Map<String, Object> additionalProperties;

    private StoreMenuResponseTree(List<MenuTree> menuConfiguration, Map<String, Object> additionalProperties) {
        this.menuConfiguration = menuConfiguration;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("menu_configuration")
    public List<MenuTree> getMenuConfiguration() {
        return menuConfiguration;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof StoreMenuResponseTree && equalTo((StoreMenuResponseTree) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(StoreMenuResponseTree other) {
        return menuConfiguration.equals(other.menuConfiguration);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.menuConfiguration);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private List<MenuTree> menuConfiguration = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(StoreMenuResponseTree other) {
            menuConfiguration(other.getMenuConfiguration());
            return this;
        }

        @JsonSetter(value = "menu_configuration", nulls = Nulls.SKIP)
        public Builder menuConfiguration(List<MenuTree> menuConfiguration) {
            this.menuConfiguration.clear();
            this.menuConfiguration.addAll(menuConfiguration);
            return this;
        }

        public Builder addMenuConfiguration(MenuTree menuConfiguration) {
            this.menuConfiguration.add(menuConfiguration);
            return this;
        }

        public Builder addAllMenuConfiguration(List<MenuTree> menuConfiguration) {
            this.menuConfiguration.addAll(menuConfiguration);
            return this;
        }

        public StoreMenuResponseTree build() {
            return new StoreMenuResponseTree(menuConfiguration, additionalProperties);
        }
    }
}
