/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.argolabs.ai.api.types;

import com.argolabs.ai.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = StoreTypeSchema.Builder.class)
public final class StoreTypeSchema {
    private final Optional<String> content;

    private final Optional<BusinessTypeSchema> businessType;

    private final Map<String, Object> additionalProperties;

    private StoreTypeSchema(
            Optional<String> content,
            Optional<BusinessTypeSchema> businessType,
            Map<String, Object> additionalProperties) {
        this.content = content;
        this.businessType = businessType;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("content")
    public Optional<String> getContent() {
        return content;
    }

    @JsonProperty("business_type")
    public Optional<BusinessTypeSchema> getBusinessType() {
        return businessType;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof StoreTypeSchema && equalTo((StoreTypeSchema) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(StoreTypeSchema other) {
        return content.equals(other.content) && businessType.equals(other.businessType);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.content, this.businessType);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> content = Optional.empty();

        private Optional<BusinessTypeSchema> businessType = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(StoreTypeSchema other) {
            content(other.getContent());
            businessType(other.getBusinessType());
            return this;
        }

        @JsonSetter(value = "content", nulls = Nulls.SKIP)
        public Builder content(Optional<String> content) {
            this.content = content;
            return this;
        }

        public Builder content(String content) {
            this.content = Optional.ofNullable(content);
            return this;
        }

        @JsonSetter(value = "business_type", nulls = Nulls.SKIP)
        public Builder businessType(Optional<BusinessTypeSchema> businessType) {
            this.businessType = businessType;
            return this;
        }

        public Builder businessType(BusinessTypeSchema businessType) {
            this.businessType = Optional.ofNullable(businessType);
            return this;
        }

        public StoreTypeSchema build() {
            return new StoreTypeSchema(content, businessType, additionalProperties);
        }
    }
}
