/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.argolabs.ai.api.types;

import com.argolabs.ai.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = StoreMenuResponseFlat.Builder.class)
public final class StoreMenuResponseFlat {
    private final Optional<List<MenuFlat>> menus;

    private final Optional<List<CategoryFlat>> categories;

    private final Optional<List<MenuItemFlat>> items;

    private final Optional<List<ModifierGroupFlat>> modifierGroups;

    private final Optional<List<ModifierItemFlat>> modifierItems;

    private final Map<String, Object> additionalProperties;

    private StoreMenuResponseFlat(
            Optional<List<MenuFlat>> menus,
            Optional<List<CategoryFlat>> categories,
            Optional<List<MenuItemFlat>> items,
            Optional<List<ModifierGroupFlat>> modifierGroups,
            Optional<List<ModifierItemFlat>> modifierItems,
            Map<String, Object> additionalProperties) {
        this.menus = menus;
        this.categories = categories;
        this.items = items;
        this.modifierGroups = modifierGroups;
        this.modifierItems = modifierItems;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("menus")
    public Optional<List<MenuFlat>> getMenus() {
        return menus;
    }

    @JsonProperty("categories")
    public Optional<List<CategoryFlat>> getCategories() {
        return categories;
    }

    @JsonProperty("items")
    public Optional<List<MenuItemFlat>> getItems() {
        return items;
    }

    @JsonProperty("modifier_groups")
    public Optional<List<ModifierGroupFlat>> getModifierGroups() {
        return modifierGroups;
    }

    @JsonProperty("modifier_items")
    public Optional<List<ModifierItemFlat>> getModifierItems() {
        return modifierItems;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof StoreMenuResponseFlat && equalTo((StoreMenuResponseFlat) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(StoreMenuResponseFlat other) {
        return menus.equals(other.menus)
                && categories.equals(other.categories)
                && items.equals(other.items)
                && modifierGroups.equals(other.modifierGroups)
                && modifierItems.equals(other.modifierItems);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.menus, this.categories, this.items, this.modifierGroups, this.modifierItems);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<MenuFlat>> menus = Optional.empty();

        private Optional<List<CategoryFlat>> categories = Optional.empty();

        private Optional<List<MenuItemFlat>> items = Optional.empty();

        private Optional<List<ModifierGroupFlat>> modifierGroups = Optional.empty();

        private Optional<List<ModifierItemFlat>> modifierItems = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(StoreMenuResponseFlat other) {
            menus(other.getMenus());
            categories(other.getCategories());
            items(other.getItems());
            modifierGroups(other.getModifierGroups());
            modifierItems(other.getModifierItems());
            return this;
        }

        @JsonSetter(value = "menus", nulls = Nulls.SKIP)
        public Builder menus(Optional<List<MenuFlat>> menus) {
            this.menus = menus;
            return this;
        }

        public Builder menus(List<MenuFlat> menus) {
            this.menus = Optional.ofNullable(menus);
            return this;
        }

        @JsonSetter(value = "categories", nulls = Nulls.SKIP)
        public Builder categories(Optional<List<CategoryFlat>> categories) {
            this.categories = categories;
            return this;
        }

        public Builder categories(List<CategoryFlat> categories) {
            this.categories = Optional.ofNullable(categories);
            return this;
        }

        @JsonSetter(value = "items", nulls = Nulls.SKIP)
        public Builder items(Optional<List<MenuItemFlat>> items) {
            this.items = items;
            return this;
        }

        public Builder items(List<MenuItemFlat> items) {
            this.items = Optional.ofNullable(items);
            return this;
        }

        @JsonSetter(value = "modifier_groups", nulls = Nulls.SKIP)
        public Builder modifierGroups(Optional<List<ModifierGroupFlat>> modifierGroups) {
            this.modifierGroups = modifierGroups;
            return this;
        }

        public Builder modifierGroups(List<ModifierGroupFlat> modifierGroups) {
            this.modifierGroups = Optional.ofNullable(modifierGroups);
            return this;
        }

        @JsonSetter(value = "modifier_items", nulls = Nulls.SKIP)
        public Builder modifierItems(Optional<List<ModifierItemFlat>> modifierItems) {
            this.modifierItems = modifierItems;
            return this;
        }

        public Builder modifierItems(List<ModifierItemFlat> modifierItems) {
            this.modifierItems = Optional.ofNullable(modifierItems);
            return this;
        }

        public StoreMenuResponseFlat build() {
            return new StoreMenuResponseFlat(
                    menus, categories, items, modifierGroups, modifierItems, additionalProperties);
        }
    }
}
