/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.argolabs.ai.api.resources.stores.requests;

import com.argolabs.ai.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ReadStoresV1StoresGetRequest.Builder.class)
public final class ReadStoresV1StoresGetRequest {
    private final Optional<Integer> skip;

    private final Optional<Integer> limit;

    private final Map<String, Object> additionalProperties;

    private ReadStoresV1StoresGetRequest(
            Optional<Integer> skip, Optional<Integer> limit, Map<String, Object> additionalProperties) {
        this.skip = skip;
        this.limit = limit;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("skip")
    public Optional<Integer> getSkip() {
        return skip;
    }

    @JsonProperty("limit")
    public Optional<Integer> getLimit() {
        return limit;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ReadStoresV1StoresGetRequest && equalTo((ReadStoresV1StoresGetRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ReadStoresV1StoresGetRequest other) {
        return skip.equals(other.skip) && limit.equals(other.limit);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.skip, this.limit);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Integer> skip = Optional.empty();

        private Optional<Integer> limit = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ReadStoresV1StoresGetRequest other) {
            skip(other.getSkip());
            limit(other.getLimit());
            return this;
        }

        @JsonSetter(value = "skip", nulls = Nulls.SKIP)
        public Builder skip(Optional<Integer> skip) {
            this.skip = skip;
            return this;
        }

        public Builder skip(Integer skip) {
            this.skip = Optional.ofNullable(skip);
            return this;
        }

        @JsonSetter(value = "limit", nulls = Nulls.SKIP)
        public Builder limit(Optional<Integer> limit) {
            this.limit = limit;
            return this;
        }

        public Builder limit(Integer limit) {
            this.limit = Optional.ofNullable(limit);
            return this;
        }

        public ReadStoresV1StoresGetRequest build() {
            return new ReadStoresV1StoresGetRequest(skip, limit, additionalProperties);
        }
    }
}
