/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.argolabs.ai.api.core;

/**
 * This class serves as the base exception for all errors in the SDK.
 */
public class ArgoLabsException extends RuntimeException {
    public ArgoLabsException(String message) {
        super(message);
    }

    public ArgoLabsException(String message, Exception e) {
        super(message, e);
    }
}
