/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.argolabs.ai.api.core;

public final class Environment {
    public static final Environment STAGING = new Environment("https://dev-api-dev.up.railway.app");

    private final String url;

    private Environment(String url) {
        this.url = url;
    }

    public String getUrl() {
        return this.url;
    }

    public static Environment custom(String url) {
        return new Environment(url);
    }
}
