/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.argolabs.ai.api.errors;

import com.argolabs.ai.api.core.ArgoLabsApiException;
import com.argolabs.ai.api.types.HttpValidationError;

public final class UnprocessableEntityError extends ArgoLabsApiException {
    /**
     * The body of the response that triggered the exception.
     */
    private final HttpValidationError body;

    public UnprocessableEntityError(HttpValidationError body) {
        super("UnprocessableEntityError", 422, body);
        this.body = body;
    }

    /**
     * @return the body
     */
    @java.lang.Override
    public HttpValidationError body() {
        return this.body;
    }
}
